### ISSUE TITLE
Write a function that tests whether a string is a palindrome.

### ISSUE THREAD

**Issue by Dhroov7** [Dhroov7/Hacktoberfest2019#104]
- Create a programs function that tests whether a string is a palindrome.
- Add that file in palindrome folder.

**Comment by rahulbisht12** [comment]
def isPalindrome(str): 

	# Run loop from 0 to len/2 
	for i in xrange(0, len(str)/2): 
		if str[i] != str[len(str)-i-1]: 
			return False
	return True

# main function 
s = "malayalam"
ans = isPalindrome(s) 

if (ans): 
	print("Yes") 
else: 
	print("No")

**Comment by munkhorgil** [comment]
Done https://github.com/Dhroov7/HacktoberFest2019/pull/106

**Comment by Abhishekkumar001** [comment]
#include <iostream>
using namespace std;
int main(){
    char string[20];
    int i, length=0;
    int flag = 0;
    cin >> string;
    //count length of a string
    while(string[length]!='\0'){
        length++;
    }
    
    for(i=0;i < length ;i++){
        if(string[i] != string[length-i-1]){
            flag = 1;
            break;
   }
}
    
    if (flag) {
        cout << string << " is not a palindrome" << endl; 
    }    
    else {
        cout << string << " is a palindrome" << endl; 
    }
    return 0;
}

**Comment by Dhroov7** [comment]
Don't add the code here.

**Comment by azinudinachzab** [comment]
#122

**Comment by omerjaved11** [comment]
#112

**Comment by omerjaved11** [comment]
fix for #104, palindrome #112

**Comment by emanuellima1** [comment]
Done in #329
