### ISSUE TITLE
Repo labelled as invalid by Hacktoberfest19

### ISSUE THREAD

**Issue by anandthegreat** [Dhroov7/Hacktoberfest2019#1043]

**Comment by amitrajitbose** [comment]
Could you please share some screenshots and more information about this? @anandthegreat

**Comment by vinitshahdeo** [comment]
If you're looking for creating PRs for HacktoberFest, **you may look into few good first issues [here](https://vinitshahdeo.github.io/HacktoberFest2K19/)** which are up for grabs.
