### ISSUE TITLE
Create an issue for new ideas.

### ISSUE THREAD

**Issue by Dhroov7** [Dhroov7/Hacktoberfest2019#121]

**Comment by JustineUgo** [comment]
Must I use recursion to solve the countDigit problem. Am I allowed to use loops?

**Comment by Lablnet** [comment]
What about to remove duplicated values from DataSets like 

``` 
    21 12 5
    54 21 3 
    65 21 6
```

**Comment by Dhroov7** [comment]
> Must I use recursion to solve the countDigit problem. Am I allowed to use loops?

Create an issue for this and also create another folder naming `countDigits`
