### ISSUE TITLE
Write a function to check lab numbers

### ISSUE THREAD

**Issue by Seniru** [Dhroov7/Hacktoberfest2019#140]
# Lab Numbers

A **lab number** is a number such that the **square** of any of its prime divisors is **still one** of its divisors.

### For example:
Input: 8
Output: true (2 is a prime divisor of 8, and 2x2=4 is also a divisor of 8)

Input: 50
Output: true (5 is a prime divisor of 50, and 5x5=25 is also a divisor of 50)

Write a program to check if the user input is a Lab number or not.

> Bonus: Print all the Lab numbers in a given range.

*Challenge from sololearn* (https://www.sololearn.com/learn/10781/?ref=app)

**Comment by ronika-das** [comment]
I would like to take this issue
