### ISSUE TITLE
Don't contribute Hacktoberfest PRs here, please.

### ISSUE THREAD

**Issue by hacktoberfest-team** [Dhroov7/Hacktoberfest2019#270]
Hi there,

Thanks for your interest in Hacktoberfest and helping others learn how to make their first contributions to open source!

That said, high-quality contributions are part of the [the core values of Hacktoberfest](https://hacktoberfest.digitalocean.com/details), so we kindly ask that you do not create repositories which allow users to quickly gain a PR toward completing the challenge.

We encourage you to take a look at our list of [Hacktoberfest issues](https://hacktoberfest.digitalocean.com/#projects) for inspiration and ideas about making meaningful contributions to open source projects.

_Due to this, we've added this repository to our known list of "spam" repositories and pull requests here will not count toward Hacktoberfest 2019._

Happy Hacking,
The Hacktoberfest Team

Hacktoberfest is presented by [DigitalOcean](https://do.co/hacktoberfest50) and [DEV](https://dev.to).

**Comment by Dhroov7** [comment]
@hacktoberfest-team Is there any way to remove my repository from the spam list?

**Comment by hacktoberfest-team** [comment]
@Dhroov7 Please reach out via email to hacktoberfest@digitalocean.com if you have any questions regarding this.

**Comment by krishnu9** [comment]
@Dhroov7, no. Hacktoberfest is an event aiming towards getting people involved with open source and making quality contributions to open source software. A repository like this is just for making people create PRs for the sake of making 4 PRs and completing the challenge.
