### ISSUE TITLE
hello world program in any programming language

### ISSUE THREAD

**Issue by Dhroov7** [Dhroov7/Hacktoberfest2019#31]
- Commit hello word program in any programming language of your own choice.

**Comment by lanuma** [comment]
can i start this and create new folder called **src** ??

**Comment by Dhroov7** [comment]
@lanuma Sure!!

**Comment by chiru091096** [comment]
Can i add hello world program in python:

**Comment by chiru091096** [comment]
Can I add hello world in C++?
